# Generated by Django 4.2.19 on 2025-03-16 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blogpost_deleted_at_blogpost_deleted_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='deleted_by',
        ),
    ]
